set(UPLOAD_METHOD_DEFAULT MBED)

set(STM32CUBE_UPLOAD_ENABLED TRUE)

if(STM32CUBE_UPLOAD_ENABLED)
    set(STM32CUBE_CONNECT_COMMAND -c port=SWD reset=HWrst)
    set(STM32CUBE_GDBSERVER_ARGS --swd)
endif()
